<?php

return [

    'DEVELOPER_DEMO' => '100',
    'GARMENT_DEMO' => '1',
    'OFFSET_DEMO' => '2',
    'AARAN_ERP' => '3',

    'SK_ENTERPRISES' => '101',
    'AARAN_INDIA_FASHION' => '102',
    'AARAN_ASSOCIATES' => '103',
    'SK_PRINTERS' => '104',
    'SRI_GANAPATHI_PRINTING_PRESS' => '105',
    'AARAN_INFO_TECH' => '106',
    'NEOT' => '109',
    'BMVIKAAS' => '110',
    'AARAN_CAPITALS' => '110',

    'PRAPTHIIMPEX' => '107',
    'SMSUPVC' => '108',

    'SARA_SCREENS' => '201',
    'COLOURS_PRINTING' => '202',
    'NEW_AMMAN_PRINTERS' => '203',
    'KGS_PRINTERS' => '204',
    'THIRUMURUGAN_PRINTERS' => '205',
    'KATHIR_PRINTERS' => '206',
    'AJ_PRINTING' => '207',
    'SAIRF_SOURCING' => '208',
    'BEST_PRINT' => '209',
    'VIP_GRAPHIICS' => '210',

    'VIJAY_GARMENTS' => '301',
    'AMAL_TEX' => '302',
    'ESSA_KNITTING' => '303',
    'ESSA_KNITTING_GARMENT' => '304',
    'VETRIVEL_GARMENTS' => '305',
    'ASHWIN_TEX' => '306',

    'MARK_INTERNATIONAL' => '307',
    'NEETHU_INDUSTRIES' => '308',
    'SRI_VENKATESWARA_TEXMART' => '309',

    'A1_IMPEX' => '310',
    'SATHYANARAYANA_GARMENTS' => '311',
    'FASHION_FABRICS' => '312',

    'VNINFOTECH' => '315',

    'SUKRAA_GARMENTS' => '316',
    'UGAN_APPARELS' => '317',
    'SEYON_FASHION' => '318',
    'SRI_SENTHUR_TEX' => '319',
    'SK_INTERNATIONAL' => '320',
    'SHONA_EXPORTS' => '321',
    'MODE_CREATIONS' => '322',
    'KARUNAAMBIKAA_EXPORT' => '323',
    'BOYANCE_INDIA' => '324',
    'ASWATH_APPARELS' => '325',
    'ATO_TEXTILES' => '326',

    'AARAN_WELFARE' => '2000',
    'SPOT_MY_NUMBER' => '3000',
    'SPORTS_CLUB' => '4000',
    'SHARES' => '5000',
];
